---
# handlers file for postgresql
- name: restart postgresql
  service:
    systemd: postgresql
    state: restarted
  become: true

- name: reload postgresql
  systemd:
    name: postgresql
    state: restarted
  become: true
